# Generated by Django 5.0 on 2024-02-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(default='ok', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='empty', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='empty', max_length=400),
            preserve_default=False,
        ),
    ]
