# Generated by Django 5.0 on 2024-02-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_profile_interests_profile_job_title_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_title',
            new_name='job_seek',
        ),
    ]
